### ISSUE TITLE
Binary string causes numbers to be dumped as hex

### ISSUE THREAD

**Issue by minus7** [nlohmann/json#101]
The following code dumps the value of the `number` field in hexadecimal format (without leading `0x`, but that's not legal json anyway afaik) when there's also a string containing a symbol between `\x00` and `\x1f`.
```cpp
#include <iostream>
#include "json.hpp"

using namespace std;
using json = nlohmann::json;

int main()
{
	int64_t number = 10;
	cout << "number: " << number << endl;
	string bytes{"\x00" "asdf\n", 6};
	cout << "bytes: " << bytes << endl;
	//json j{{"int64", number}, {"binary string", bytes}};
	json j;
	j["int64"] = number;
	j["binary string"] = bytes;
	cout << j.dump() << endl;
	return 0;
}
```

The output looks like this:
```
number: 10
bytes: asdf

{"binary string":"\u0000asdf\n","int64":a}
```

Using the latest revision (540c58964dba265453d13c43ffd93a21504c4157)

**Comment by nlohmann** [comment]
I can reproduce the error. I have no idea yet why the `dump()` function decides to print the number as hex, but the library seems to be confused by the control character inside the string. I'll continue checking.

**Comment by nlohmann** [comment]
I found the reason for the problem: The control characters need to be escaped as `\uxxxx`. In that part of the code, an internal string stream is configured to print the character as hexadecimal number. This needs to be reset, because otherwise all subsequent numbers would be printed as hexadecimal (`a` instead of `10`).
