### ISSUE TITLE
Ternary operator crash

### ISSUE THREAD

**Issue by parfenuk** [nlohmann/json#1034]
This simple code crashes:
`string someStr;`
`json j = json::object();`
`// the next line crashes`
`j["someKey"] = someStr.empty() ? nullptr : someStr;`

However, if I use standard if-else condition, everything is fine:
`string someStr;`
`json j = json::object();`
`// the code below works ok`
`if (someStr.empty()) j["someKey"] = nullptr;`
`else j["someKey"] = someStr;`

Also if S is not empty - both versions work. 
Is it a bug or feature? :)

I'm using GNU C++ 14 compiler, IDE Xcode 9.3

**Comment by nlohmann** [comment]
The types in `someStr.empty() ? nullptr : someStr` seems to be treated as `const char*` then yields `j["someKey"] = (const char*)nullptr;` which calls `std::string(nullptr)` which yields the error.

I have no idea how to tell the compiler that `someStr.empty() ? nullptr : someStr` should be treated as `json` other than to make it explicit:

```cpp
j["someKey"] = someStr.empty() ? json(nullptr) : json(someStr);
```

**Comment by gregmarr** [comment]
A single type is deduced based on the types of the two values of the ternary operator.  There is no type that works properly for `nullptr` and `std::string` here.  That requirement is not there for the if/else. If you want the type to be `null` for an empty `someStr` instead of an empty string, you need to use the if/else.  Otherwise, there's no point in even having the check, and you can simply do `j["someKey"] = someStr;`.

**Comment by parfenuk** [comment]
Yes, I indeed need the field being null for empty strings, and I was able to solve it. 
Thank you, guys, for telling me two different solutions and for an information about how ternary operator works.
