### ISSUE TITLE
Commented out test cases, should they be removed?

### ISSUE THREAD

**Issue by whackashoe** [nlohmann/json#1060]
I found a few files with commented out test cases, wondering if they should be kept or banished to git history

---

test/src/unit-allocator.cpp

test/src/unit-cbor.cpp

test/src/unit-regression.cpp

test/src/unit-ubjson.cpp

test/src/unit-class_lexer.cpp

test/src/unit-regression.cpp

**Comment by nlohmann** [comment]
You are right - there are several commented-out test cases. I need to check for the individual reasons for those. I think in the case for the binary formats, it is just laziness from my side, because I copied the test file from CBOR, made some adjustments, and commented-out all tests that could not be adjusted.

**Comment by nlohmann** [comment]
I had a look at the test cases and adjusted them. Thanks for noting!
