### ISSUE TITLE
Unexpected behaviour of is_null

### ISSUE THREAD

**Issue by phyz777** [nlohmann/json#1112]
The following code produces unexpected output (which is, _all_ four statements being printed): 

```cpp
#include <iostream>

#include "json.hpp"

int main()
{
    nlohmann::json j;

    if (j.empty()) {
        std::cout << "Object is empty" << std::endl;
    }

    if (j.is_null()) {
        std::cout << "Object is null" << std::endl;
    }

    nlohmann::json k;

    j["aminull"] = k;

    if (j["aminull"].empty()) {
        std::cout << "Object under key is empty" << std::endl;
    }

    if (j["aminull"].is_null()) {
        std::cout << "Object under key is null" << std::endl;
    }

    return 0;
}

```
I am not entirely sure whether or not this is the expected behaviour, but I think it would be more intuitive to have only the empty() conditions evaluate to true and the others to false? 

Best wishes and thanks for the great work!

**Comment by phyz777** [comment]
By the way, the following works as expected: 

```
    nlohmann::json l = nlohmann::json::object();

    if (l.empty()) {
        std::cout << "Object is also empty" << std::endl;
    }

    if (l.is_null()) {
        std::cout << "Object is also null" << std::endl;
    }
```

If all of this is intended to work like this: sorry for the hassle and please, feel free to silently delete this issue.

**Comment by nlohmann** [comment]
Please note:

- Uninitialized JSON values are `null` by default.
- `empty()` returns true if and only if `size() == 0`.
- `null` values have the size 0, because they have no value (see [documentation](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a1a86d444bfeaa9518d2421aedd74444a.html#a1a86d444bfeaa9518d2421aedd74444a)).
- objects/arrays are empty if they have no entries.

In your second example, I do not believe that `l.is_null()` is true.

**Comment by phyz777** [comment]
Yes, indeed, is_null does not evaluate to true here, this is what I meant with 'works as expected'. 
Well, in this case, everything is just fine. Feel free to delete or close this issue. (:

**Comment by nlohmann** [comment]
No worries - every ticket may be helpful for others and give me an idea what needs to be documented more thoroughly.
