### ISSUE TITLE
chars get treated as JSON numbers not JSON strings

### ISSUE THREAD

**Issue by zoe-mcelderry** [nlohmann/json#1139]
- What is the issue you have?

I am creating some JSON from some C++ datatypes, one of which is the char datatype.  I would expect this to be treated as a JSON string, but when I call the dump method it outputs the value as if it were a JSON number.

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

nlohmann::json json;
char sample = 'a';
json["char"] = sample;
std::cout << json.dump ();

- What is the expected behavior?

Expect the output to show : {"char":"a"}

- And what is the actual behavior instead?

The output I get is : {"char":97}

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

OS is Debian 9.3, compiler is g++ 6.3.0

- Did you use a released version of the library or the version from the `develop` branch?

Tag v3.1.2

**Comment by nlohmann** [comment]
This is known behavior (can’t find the respective issue right now) which can’t be fixed. It should be better explained in the documentation though.

**Comment by zoe-mcelderry** [comment]
Ok, thanks anyway.  Apologies for raising a duplicate.

**Comment by OvermindDL1** [comment]
For note, your expected output of `"a"` is not a character, but rather it's string (null-terminated once parsed), and what should happen if the input 'string' was multi character for example?  An integer is the only logical representation of a character in JSON since JSON doesn't have a specific character type.

Plus a char is just a 1-byte integer, hard to distinguish that from, say, an actual 1-byte integer.  ^.^

**Comment by nlohmann** [comment]
Related: #1052 #276

**Comment by nlohmann** [comment]
@zoe-mcelderry No worries. I shall leave #1052 open as we should mention this in the documentation.
