### ISSUE TITLE
Value throws on null string

### ISSUE THREAD

**Issue by p-groarke** [nlohmann/json#1163]
Take for example `{ "key" : null }`.

Using `value("key", "")` on a null string throws `[json.exception.type_error.302] type must be string, but is null`.

Expected behavior : Use default value.

**Comment by nlohmann** [comment]
I do not fully understand your issue. Could you provide actual example code?

**Comment by p-groarke** [comment]
For example,
```
	nlohmann::json _j = nlohmann::json::parse("{\"test\" : null}");
	std::string val = _j.value("test", "");
```

**Comment by p-groarke** [comment]
I guessed that much, I would like to challenge that however ;)

In a perfect world where API makers would follow the JSON spec perfectly, the current solution would work great. However, reality is quite different. I don't see any downsides to modifying `value` to deal with this sort of issue. `get<>` offers a great alternative if you want to deal with exceptions.

Note that with the current behavior, one would need to check every single string for null. Which is madness when using huge APIs. Since if an end-point returns null for 1 empty string, it means any empty string may be null.

Willing to discuss?

**Comment by p-groarke** [comment]
Note that I am only talking about `null`, which is a special snowflake. Using `value` to parse an `int` into a `string` should throw.

**Comment by p-groarke** [comment]
Null is used to denote empty strings, 0 isn't. Documentation lets you know what to expect.

@nlohmann yes or no?

**Comment by nlohmann** [comment]
@p-groarke I am not sure what you mean in https://github.com/nlohmann/json/issues/1163#issuecomment-405106723. An empty string is `""`. `null` just means "no value", but has no type.

I agree with @gregmarr that `null` is not a special value and hence would not need special treatment, see the [documentation of `value`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_adcf8ca5079f5db993820bf50036bf45d.html#adcf8ca5079f5db993820bf50036bf45d). Changing the function's semantics would be a breaking change which I would not be willing to do, because it would mean for people to adjust their code. Adding a new function with special semantics for `null` values could be possible, but could also be realized with the public API.

**Comment by p-groarke** [comment]
Alright.

**Comment by 2beens** [comment]
@nlohmann 
Sorry for writing here again, but I have a similar problem with the following code:
`std::map<std::string, std::vector<std::string>> parsedParams = json::parse(parametersJson);`
where `parametersJson` is a string of value: `{ "eventToken" : [null] }`.
The exception I get is:

> abort_message: assertion "terminating with uncaught exception of type nlohmann::detail::type_error: [json.exception.type_error.302] type must be string, but is null" failed

Is there any way I can get this map, which has only one element (of key `eventToken`) and null value?
Can you please suggest something else if not?

Thanks a lot, and sorry for any inconveniences!

**Comment by nlohmann** [comment]
I fear there is no easier solution than to manually filter the array at key "eventToken" from elements that are not strings.

Example (using https://en.wikipedia.org/wiki/Erase%E2%80%93remove_idiom):

```cpp
#include <iostream>
#include "json.hpp"

using json = nlohmann::json;

int main() {
    json j = {"foo", nullptr, "bar", 1};
    j.erase(std::remove_if(j.begin(), j.end(), [](json& el) { return not el.is_string(); }), j.end());
    std::cout << j << std::endl;
}
```

Output:

```
["foo","bar"]
```

**Comment by 2beens** [comment]
@nlohmann OK, thanks a lot, I will try this approach or something similar.

**Comment by p-groarke** [comment]
@2beens you can use a parse indirection for your data types to deal with these issues. This has the nice side effect of being easily extensible with `if constexpr` and friends.

```
template <class T>
inline void get_v(const nlohmann::json& j, const char* key, T& val) {
	if (j.at(key).is_null()) {
		val = T{};
	} else {
		val = j.value(key, T{});
	}
}

```

**Comment by Luperco** [comment]
Hi, sorry to resurrect such old conversation.

I understand that there are good alternative to handle null values rather than change the library. 

Anyway I cannot find anything when using the macros NLOHMANN_DEFINE_TYPE_INTRUSIVE and NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE.
Is there a way to check for null value without writing to_json() and from_json() manually?

Thanks.

**Comment by nlohmann** [comment]
No, `NLOHMANN_DEFINE_TYPE_INTRUSIVE` and `NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE` only allow to list the members you would like to serialize/deserialize, but do not offer any customization (like how to cope with `null` values). If you want any behavior other than the default behavior provided by those macros, you must define the `to_json`/`from_json` functions yourself.

**Comment by Luperco** [comment]
Ok, I understand. 

Thank you anyway.

**Comment by pavik** [comment]
@Luperco not the best but possible workaround, just before `NLOHMANN_DEFINE_TYPE_INTRUSIVE ` redefine `NLOHMANN_JSON_FROM`
```
// ignore null and missing fields
#undef NLOHMANN_JSON_FROM
#define NLOHMANN_JSON_FROM(v1) {\
auto iter = nlohmann_json_j.find(#v1);\
if (iter != nlohmann_json_j.end())\
    if (!iter->is_null())\
        iter->get_to(nlohmann_json_t.v1); }
```

**Comment by Luperco** [comment]
Thanks @pavik 

that seems better than rewrite from_json(). I'll give it a try.
