### ISSUE TITLE
Find and Count for arrays

### ISSUE THREAD

**Issue by alvarolb** [nlohmann/json#117]
Not sure if this has been already discussed, but I find useful to implement the find and count methods also for arrays. Arrays can store multiple items, so count can be useful to check wether a item is present of how many times it appears. However I don't know if it is easy to develop taking into account that an array can store multiple value types.

**Comment by nlohmann** [comment]
These functions could indeed be easily implemented using find (http://en.cppreference.com/w/cpp/algorithm/find) and count (http://en.cppreference.com/w/cpp/algorithm/count) from the STL's algorithms.

However, I am not sure how the `find` function should work for an array, because if an element is stored several times, which iterator shall be returned?
