### ISSUE TITLE
Check value for existence by json_pointer

### ISSUE THREAD

**Issue by 3galki** [nlohmann/json#1194]
I have found no proper way to check element existence.
I can use `json.at("..."_json_pointer)` but it will throw an exception if it is missed.
I can use `json.value()` method. But I have to do it twice to check all cases (or use default that will not used in my json).

**Comment by 3galki** [comment]
yep, now I have looked in code. So, looks like I have to avoid such logics...

**Comment by nlohmann** [comment]
Related: #1017

**Comment by ArnCarveris** [comment]
@nlohmann I need this `json.find("..."_json_pointer)`

**Comment by 3galki** [comment]
> json.find("..."_json_pointer)
Just one question, what value should be for end() in this case?

**Comment by ArnCarveris** [comment]
@nlohmann Hmm good question, in mind answer is `json.end()`, but this is way not obvious. 

Problem is what `json.value("..."_json_pointer, /*default*/)` throws exception when object in path not found.

**Comment by nlohmann** [comment]
The issue is that iterators of different containers cannot be compared as this would be undefined behavior.

Therefore, writing code like

```cpp
if (j.find("/foo/bar"_json_pointer) != j.end())
  ...
```

is not possible.

**Comment by ArnCarveris** [comment]
@nlohmann Ok, maybe this: `json.seach<std::string>("/foo/bar"_json_pointer, [](const auto& value) {});`?

**Comment by nlohmann** [comment]
Passing a lambda feels strange. I'd rather pass a `std::pair<bool, json::iterator>` with the bool indicating whether the search was successful (asserting the iterator can be dereferenced).

**Comment by nlohmann** [comment]
What would `value` mean in this situation?

**Comment by 3galki** [comment]
You may try to get value() work without exceptions. It will help in most cases. Additional, you can add some value, that can't be found in json, and use it as default.
Or you can look at std::optional

**Comment by nlohmann** [comment]
There is no solution for the issue yet. That's why it was closed eventually.

**Comment by 3galki** [comment]
1. You can do something like std::string::npos for your find (in this case all  containers should have same end())
2. You can make it by using std::optional but only for c++14 :)
3. You can make your own "optional" class. And implement it by `using optional = std::optional;` if c++14 or higher was used

**Comment by nlohmann** [comment]
1. What should the function return in case of success?
2. That is not an option.
3. That is not really an option.

**Comment by 3galki** [comment]
1. the same as a typical find method returns (iterator). Yes. I haven't see absolutely good solution to.

Why you do not want to do your own std::optional? It would be modern solution (but should be not called find I think) :)

**Comment by ArnCarveris** [comment]
@nlohmann 

Maybe this?
`float* value = json.get_if<float>("..."_json_pointer);`

**Comment by jaredgrubb** [comment]
I don't like the idea that it would return a ```pair<bool, json::iterator>``` because at that point i would expect the iterator to have some kind of _meaning_. For example, if I took that iterator and did iterator-ish things to it, what does it mean? Sure, I can ask "it == end" to mean "not found", but what is it the _end_ of? What does it mean if I increment that iterator? Which iterator concept does it model?

If you really want _iterators_, then I think you need to have a different kind of iterator, because you're modeling the structure very different. I think this is a bit like [directory_iterator](https://en.cppreference.com/w/cpp/filesystem/directory_iterator) versus [recursive_directory_iterator](https://en.cppreference.com/w/cpp/filesystem/recursive_directory_iterator), where the first can only iterate across one level (like json::iterator), and the second can iterate across a full tree. I think drawing inspiration from <filesystem> might be helpful.

On the other hand, doing the ```get_if``` like @ArnCarveris suggests seems simple enough, but there's something about it that feels like it's too loose. For example, I'm effectively getting an interior pointer into the object, but knowing the rules on how long that pointer is valid would be very hard to pin down. But you could just say "the pointer is valid until any part of it or its surrounding containers (and so forth) are modified", and maybe that fixes that? I don't know. I think we'd have to think this through.

Does anyone have any prior art on other ways that boost or STL or some other solid library has offered a "reach inside some arbitrary heterogenous tree structure" has approached this? I can't imagine we're the first ones :)

**Comment by nlohmann** [comment]
I would not like to add our own implementation of `std::optional` to the library. As @jaredgrubb also pointed out: JSON pointers are not iterators - especially since they lack a means to describe the "past the end" position to indicate "not found". Unless we find a way to express the result of such a function, we cannot really proceed here.
