### ISSUE TITLE
While compiling got 76 errors

### ISSUE THREAD

**Issue by officefish** [nlohmann/json#1255]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2100	illegal indirection	test-capacity	json.hpp	278	
Error	C1903	unable to recover from previous error(s) test-capacity	json.hpp	481	
Error	C2100	illegal indirection	test-unicode json.hpp	278	
Error	C2100	illegal indirection	test-testsuites json.hpp	278	
... finally even with 76 error all of them is c2100 json.hpp 278 or c1903 json.hpp 481

**Comment by nlohmann** [comment]
Which version of the library are you using? Which compiler are you using?

**Comment by officefish** [comment]
I downloaded .zip right now. Seems it is last one.

**Comment by nlohmann** [comment]
Please fill the required information:

- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by officefish** [comment]
Please describe the steps to reproduce the issue. Can you provide a small but working code example?I 

downloaded .zip 
unzip it 

$ mkdir build
$ cd build
$ cmake .. 
(ok created vs15 project)

cmake --build .
$ ctest --output-on-failure
(got errors)

go to vs15 open nlohmann_json.sln Run Build got the same errors

What is the expected behavior?

expected compilation with no errors and running all unit-tests

**Comment by nlohmann** [comment]
Please answer the questions above:

- What is the actual behavior instead?

*Please copy/paste the complete error messages*

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

*Please provide the concrete compiler version*

**Comment by officefish** [comment]
Windows 7 Home
The compiler is commonly called "Visual C++ 2015". (I am not sure, sorry rather novice in c++)

**Comment by nlohmann** [comment]
The library only works for Microsoft Visual C++ 2015 / Build Tools 14.0.25123.0 (and possibly later). Please make sure whether your version is not too old.

Furthermore, please provide details on the error messages.

**Comment by officefish** [comment]
Okey, thank you. Suppose something wrong with my environment.

**Comment by nlohmann** [comment]
Do you need further assistance?
