### ISSUE TITLE
CodeBlocks IDE can't find `json.hpp` header

### ISSUE THREAD

**Issue by DragonOsman** [nlohmann/json#1318]
I installed CodeBlocks in my Ubuntu VM and am using the LLVM Clang compiler toolchain on it instead of GCC.  I wanted to build my project on CodeBlocks on Linux and then run it through GDB since I'm having a logic error that's making it crash under Linux (I built it manually on the command line).  But when I try to build it, CodeBlocks can't find `json.hpp` in `/usr/local/json/single_include`.  I've set that path in the comiler's Search Directory, but it still can't find it.  The code is the same one I've been using working on for a while now.  

Edit: Never mind.  I wasn't doing `#include nlohmann/json.hpp`.  I fixed that error, but now I have other errors.

**Comment by nlohmann** [comment]
Please provide the information asked in the issue template:

- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?
