### ISSUE TITLE
How to parse multi object json from file?

### ISSUE THREAD

**Issue by ufosky** [nlohmann/json#1470]
I have followed this issue https://github.com/nlohmann/json/issues/367, but when my file contains whitespaces at the end, it will throw parse error exception. Is there a way to parse this file normally?

The file content like this, there are some whitespace lines at the end:
```
{"a":1}
{"a":2}


```
The code：
```
void JsonLoader::load_messages(const char *filepath,
                               std::deque<google::protobuf::Message *> *out_msgs) {
  out_msgs->clear();
  nlohmann::json j;
  std::ifstream fs(filepath);
  int index = 0;
  while (fs.peek() != EOF) {
    try {
      fs >> j;
    } catch (nlohmann::json::exception &e)
    {
      LOG(WARNING) << "    std::exception:" << e.id << " " << e.what() << std::endl;
      break;
    }

    ++index;
    LOG(WARNING) << "Load " << index << "-th json.";
    if (!j.empty()) {
      google::protobuf::Message *request = _request_prototype->New();
      Pb2Json::Json2Message(j, *request, true);
      out_msgs->push_back(request);
      LOG(WARNING) << "Loaded " << out_msgs->size() << " jsons";
    }
  }

}
```

**Comment by nlohmann** [comment]
In order to asses your issue, we need the following information:

- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by nickaein** [comment]
Each call of `fs >> j;` lead to reading one JSON from file and leaving stream at where the parsing has ended. When the parser is called for the third time, there is no JSON available in the rest of file contents and that's causes an exception as there is no valid JSON.

I believe this is an expected behavior. This is basically same as having an input file containing only white-spaces. Your solution to continue reading and `break` on exception seems fine. Is there any reason to avoid it?
One other solution is to manually skip over the whitespace characters until you reach an non-space character or end of file.
