### ISSUE TITLE
Output and input matrix

### ISSUE THREAD

**Issue by AntonPolevoi** [nlohmann/json#1544]
Hello! How can I input or output matrix in the JSON file?

**Comment by nlohmann** [comment]
In order to asses your issue, we need the following information:

- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by AntonPolevoi** [comment]
I just want to do  this one:(example on the photo)
![Снимок экрана от 2019-03-24 09-49-39](https://user-images.githubusercontent.com/48867176/54876038-45e0fe00-4e1a-11e9-9902-ef285ed677a2.png)
But I only can do it with a lot of space, like this: 
stdout:
![Снимок экрана от 2019-03-24 09-54-54](https://user-images.githubusercontent.com/48867176/54876138-89883780-4e1b-11e9-98cc-7f005a8f26ed.png)
my working code: 
![Снимок экрана от 2019-03-24 09-55-58](https://user-images.githubusercontent.com/48867176/54876139-9147dc00-4e1b-11e9-860a-e79597c994bd.png)
![Снимок экрана от 2019-03-24 10-02-00](https://user-images.githubusercontent.com/48867176/54876154-ec79ce80-4e1b-11e9-94ea-0b922f3f3df6.png)

How can I change this situation?
my operating system: Ubuntu 18.04, g++ compiler
thank you for feedback!

**Comment by nlohmann** [comment]
This kind of pretty-printing is not possible. You can try `j.dump()` for a compact representation or `j.dump(2)` (or any other integer) for indented output.

**Comment by AntonPolevoi** [comment]
thanks for your quick reply!
