### ISSUE TITLE
Integrating with android ndk issues.

### ISSUE THREAD

**Issue by roshanpatel6040** [nlohmann/json#1547]
Hi, 
How can i integrate these library with android ndk using cmake.
Currently i am getting error "You have called ADD_LIBRARY for library json without any source files."
Any help would be appreciated.

**Comment by nlohmann** [comment]
In order to asses your issue, we need the following information:

- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by roshanpatel6040** [comment]
Hi @nlohmann 
Till now i am able to integrate and use this library function in my cpp. Using include_directories(path to your include) but the issue is right now it is conflicting some opencv function.
I am using linux, ndk version 19.2.

**Comment by nlohmann** [comment]
I am no expert on Android NDK, but with the information you gave, I cannot provide any assistance. Is it an issue if the CMake integration? Please provide more information, like example code, concrete error messages - https://github.com/nlohmann/json/issues/1547#issuecomment-476250588
