### ISSUE TITLE
push_back()/emplace_back() on array invalidates pointers to existing array items

### ISSUE THREAD

**Issue by scoult3r** [nlohmann/json#1586]
I am serializing some internal structures to Json and would like to populate an array with null json values, storing a pointer to each null value and then later filling that value with the appropriate data. Eg:
```   
    json arr = json::array();
    arr.emplace_back(nullptr);
    auto* ptr0 = &arr.at(0);
    arr.emplace_back(nullptr);
    auto* ptr1 = &arr.at(1);
    arr.emplace_back(nullptr);
    auto* ptr2 = &arr.at(2);
    //Some time later:
    *ptr0 = 0;
    *ptr1 = 1;
    *ptr2 = 2;
```
However, this apparently yields an array where the first two elements are null, and only the last element in the array contains the actual data (an integer == 2).

I am not sure if I am simply using the API incorrectly, or there is an actual issue that needs to be addressed. I would very much appreciate any help, thanks!

**Comment by nickaein** [comment]
By default, JSON library uses `std::vector` data structure for storing JSON arrays. Therefore calling [`std::vector::emplace_back()`](https://en.cppreference.com/w/cpp/container/vector/emplace_back) or [`std::vector::push_back`](https://en.cppreference.com/w/cpp/container/vector/push_back) invalidates the iterators (and pointers in your case) when the `capacity()` is less or equal than `size()`.

You can: 

1. Get reference to the items after `emplace_back` calls are done.
2. Reserve the vector capacity beforehand. Since the JSON library API doesn't expose [`reserve()`](https://en.cppreference.com/w/cpp/container/vector/reserve), you should first get a pointer/reference to the underlying `std::vector` and then call `reserve()` on it. This is discussed at https://github.com/nlohmann/json/issues/1157 and https://github.com/nlohmann/json/issues/1057 for `resize()` method and you can adapt it for `reserve()`.

**Comment by scoult3r** [comment]
The sized constructor from #1057 suited my needs perfectly, thank you.
