### ISSUE TITLE
json parser crash if having a large number integer in message 

### ISSUE THREAD

**Issue by alexhhj** [nlohmann/json#1602]
- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?
I have a test case running on this json library .
The message is as below 
{
    "testList": [
        {
            "id": "160013002243",
            "customerNumber": 111000000000000000009999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999977777777777777777777777777777777777774444444444444444444444444444444444444444444444444499999999999999999999999999444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444,
            "name": "Alex Test for Json",
        },
    ]
}
Then the json parser crashes even with try-catch in C++.

It could work well if the "customer Number" is string type with "".

I am running on a Linux system on am335x.

Linux version 4.4.19 (jenkins@imvisionfw) (gcc version 5.2.0 (crosstool-NG crosstool-ng-1.22.0) ) #1 PREEMPT Thu May 16 04:11:13 CDT 2019

JSON for Modern C++ version  is 3.5.0

**Comment by gregmarr** [comment]
It's probably throwing an out of range exception from the parser.  Are you catching exceptions?

**Comment by alexhhj** [comment]
try 
				{  
					//valid_json = true;
					json::parse(request_post);
				}
				catch (json::parse_error& e)
				{
					//valid_json = false;
				printf("load JSON error %s %d message %s  n", __FUNCTION__, __LINE__, e.what());
					
				}
Just try and catch .

**Comment by nickaein** [comment]
For out of range numbers, exception [`nlohmann::json::out_of_range`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a28f7c2f087274a0012eb7a2333ee1580.html#a28f7c2f087274a0012eb7a2333ee1580) will be thrown.

When in doubt, catch the base class [`nlohmann::json::exception`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a9a0aced019cb1d65bb49703406c84970.html#a9a0aced019cb1d65bb49703406c84970) to make sure you no exception can escape:

```cpp
try 
{  
    json::parse(request_post);
}
catch (json::parse_error& e)
{
    std::cout << "Parse error:" << e.what() << std::endl;
}
catch (json::out_of_range& e)
{
    std::cout << "Out of range:" << e.what() << std::endl;
}
catch (json::exception& e)
{
    std::cout << "JSON exception: " << e.what() << std::endl;
}
// not really needed 
catch (std::exception& e)
{
    std::cout << "Unknown exception" << e.what() << std::endl;   
}
```

**Note:** The `std::exception` block is not needed since all library exceptions are derived from `json::exception`. If in some case the library throws `std::exception`, I believe it is considered as a bug.

**Comment by alexhhj** [comment]
Thanks
