### ISSUE TITLE
Converting json::value to int

### ISSUE THREAD

**Issue by JiazhengSun** [nlohmann/json#1605]
So my json looks like this:
`{
    "22" : {
           "multi" : 2,
            func : [{type: "A", "number" : [1,2,3]}]
     }
}`

I want to get the value of "multi", which is 2. The code I have now looks like this:
`
for (auto& el : j.items()) {
    auto mul = el.value()["multi"];
}
`
It says that what I am getting is json::value type. I am wondering how to access it as an integer, as that's what I put in the json? Thanks.

**Comment by JiazhengSun** [comment]
OK I think I solved it (maybe)? I make the value of "22" as another json (tmp), and access that 2 with tmp["multi"]. I am not sure if this is the best solution. If there is a better one please enlighten me. If not you may feel free to close the issue. Awesome lib! :)

**Comment by nickaein** [comment]
With `auto x = tmp["multi"]` you still get a `json::value` type for `x`, right? A workaround is to pin down the type, e.g. `int x = tmp["multi"];`. This triggers an implicit type conversion which [is NOT recommended](https://github.com/nlohmann/json#implicit-conversions).

Instead, you should use APIs like [`basic_json::get()`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_aa6602bb24022183ab989439e19345d08.html#aa6602bb24022183ab989439e19345d08).

Here is the live example: https://wandbox.org/permlink/g1vk224CUdRv3JTv

Also, double quotations are required around `func` and `type` fields in JSON, otherwise it is not valid.

**Comment by nlohmann** [comment]
@JiazhengSun Do you need further assistance?
