### ISSUE TITLE
C2440 in vs2015 cannot convert from 'initializer-list' to nlohmann::basic_json

### ISSUE THREAD

**Issue by luomomo** [nlohmann/json#1655]
errror C2440: cannot convert from 'initializer-list' to nlohmann::basic_json

- it seems no no one have met this before

- vs2015

- verson 3.6.1
 Sorry ,I don't know how to solve this

**Comment by nickaein** [comment]
Can you give a simple code example that demonstrates this issue?

**Comment by nlohmann** [comment]
In order to asses your issue, we need the following information:

- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by nlohmann** [comment]
@luomomo Could you comment on this?
