### ISSUE TITLE
 Build For Raspberry pi , Rapbery with new Compiler C++17

### ISSUE THREAD

**Issue by bnadem** [nlohmann/json#1671]
i want to compiler json.hpp for raspbery pi with c++ 17 , when i  try from Make file i becothe folowing code error: ? 

include file cassert is already included?

/json.hpp:7914:17: error: ‘assert’ was not declared in this scope
assert(x.f != 0);

warning: there are no arguments to ‘assert’ that depend on a template parameter, so a declaration of ‘assert’ must be available [-fpermissive]
assert(utf8_bytes_filled > 0);
the System ist raspbery pi with new compiler gcc-9.1.0

the version ist the new
is any Idea Please? Thanks

**Comment by nlohmann** [comment]
In order to asses your issue, we need the following information:

- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by bnadem** [comment]
Thnak for Replay
    What is the issue you have?
can't my project with  your single Header file json.hpp
 What is the expected behavior?
i try just only compiling, i have tried in  Linux , this work fine with new compiler, old Compiler, but in Raspberry Pi, i can't, i becomme alway error "assert is not defined", in Your Header is already included
   

    And what is the actual behavior instead?
cassert is already defined in your header, 
    Which compiler and operating system are you using? Is it a supported compiler?
Compiler is C++9.1 with Flag -std=c++17

    Did you use a released version of the library or the version from the develop branch?
No i have stabile version, cloned and installed in Rapbery Pi, but i can't compiler with my Project
    If you experience a compilation error: can you compile and run the unit tests?

**Comment by nlohmann** [comment]
You can try to define `NDEBUG` while compiling to switch off assertions, see https://en.cppreference.com/w/cpp/error/assert for more information.

**Comment by bnadem** [comment]
thank you is working, but i want to know why he does working without flag, 
you can close this issue, Thank you

**Comment by nlohmann** [comment]
I also have no idea. I guess the compiler has a buggy library. You may also want to try to change the include `<cassert>` by `<assert.h>`.
