### ISSUE TITLE
Qt deprecation model halting compiltion

### ISSUE THREAD

**Issue by v71** [nlohmann/json#1675]
i have included json.hpp as a single file in a qt project using the msvc17 compiler in release mode
i get several of these errosr:
attribute 'deprecated'(since 3.0.0 ) cannot be used in this context
I don't know if commenting out the offending lines might cause a mjor disruption in the function of the library.

**Comment by nlohmann** [comment]
In order to asses your issue, we need the following information:

- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by v71** [comment]
compiler error

incldue "json.hpp" in a qt cretor project with msvc2017 32 bit release option enabled

the expected behaviour is to copile without errors

i have uysed the latest ( non develop branch) version

no i can't

**Comment by nlohmann** [comment]
What is the exact compiler error message?

**Comment by v71** [comment]
the exact compiler message is :

C:\Users\Vincenzo Panella\Desktop\qtprojects\levgen4_8\json.hpp:20486: error: C2416: l'attributo 'deprecated("Since 3.0.0")' non può essere applicato in questo contesto

which translates:

C:\Users\Vincenzo Panella\Desktop\qtprojects\levgen4_8\json.hpp:20486: error: C2416: attribute 'deprecated("Since 3.0.0")' cannot be applied in this context

**Comment by OvermindDL1** [comment]
@v71 It's not a `json` bug, it's a MSVC bug, known and fixed in the version after:
https://developercommunity.visualstudio.com/content/problem/138957/wrong-compilation-error-for-deprecated-nested-frie.html

Either downgrade or upgrade to whatever version of MSVC has been released in 2019.
