### ISSUE TITLE
How to deserialize arrays  from json

### ISSUE THREAD

**Issue by WhoseTheNerd** [nlohmann/json#1681]
- Describe what you want to achieve.
I want to get `std::vector`s from json
```json
{
  "vertices": [
    3.227124,
    ...
  ],
  "textureCoords": [
     0.863038,
     ...
  ],
  ...
}
```

- Describe what you tried.
I tried code below, and got confused what `j.get()` does or works, since there is no wiki on this repo
```c
auto j = json::parse(json);
std::vector<float> positions;
positions = j["vertices"];
```

- Describe which system (OS, compiler) you are using.
Ubuntu 18.04 LTS 
```
$ gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

- Describe which version of the library you are using (release version, develop branch).
develop branch by just putting it into the project.

**Comment by nlohmann** [comment]
This code works:

```cpp
#include "json.hpp"

using json = nlohmann::json;

int main()
{
    json j;
    j["vertices"] = {3.227124, 1.1, 2.2, 3.3, 4.4};
    
    std::vector<float> positions;
    j["vertices"].get_to(positions);
}
```

**Comment by Faaux** [comment]
Is it by design that get_to appends to the vector? Wondering since you are reserving in json.hpp like this:
`arr.reserve(j.size());` without considering the size the std::vector already has.

Repro:
`
nlohmann::json j;
j["vertices"] = {1.0};

std::vector<float> positions = {2.0};
j["vertices"].get_to(positions);

assert(positions.size() == 2)
`

which means the reserve call should take the current size into account.

**Comment by WhoseTheNerd** [comment]
Thank you, that code worked fine. Closing an issue.
