### ISSUE TITLE
not linking properly with cmake

### ISSUE THREAD

**Issue by Faunsce** [nlohmann/json#1709]
Using conan and cmake with the provided conan link inside my conanfile.txt, this library does not work at all. i can't access any of the code or files.
I link sfml the exact same way yet sfml works like any other conan integrated library while this library does not.

**Comment by nlohmann** [comment]
In order to asses your issue, we need the following information:

- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by nlohmann** [comment]
As the README states: Please file issues on Conan here: https://github.com/vthiery/conan-jsonformoderncpp/issues

> If you are using Conan to manage your dependencies, merely add jsonformoderncpp/x.y.z@vthiery/stable to your conanfile.py's requires, where x.y.z is the release version you want to use. Please file issues here if you experience problems with the packages.

(from https://github.com/nlohmann/json#package-managers).

**Comment by Faunsce** [comment]
Ok. I've opened an issue there. to be more clear, im forced to use the cmake method, `find_package` which isnt necesarry for the other 4 packages my program uses which increases the complexity of the cmake file due to subsequent necesarry cmake commands far more than i like by inhibiting my ability to use just 1 foreach loop per build target (release, debug, etc). If this still sounds like a maintainer problem and not a package creator problem then you are welcome to close this issue.

**Comment by nlohmann** [comment]
Thanks for checking back!
