### ISSUE TITLE
Combined find_package/add_subdirectory not linking libraries

### ISSUE THREAD

**Issue by phuntimes** [nlohmann/json#1771]
### Describe what you want to achieve.

I'm trying to follow the CMake example of [Supporting Both][1]. 

### Describe what you tried.

The [external example][2] works as expected. Unfortunately, the former encounters a namespace error. With `extern/CMakeLists.txt`

``` cmake
if(USE_EXTERNAL_JSON)
    message(DEBUG " using external library for nlohmann JSON")
    find_package(nlohmann_json 3.2.0 REQUIRED)
else()
    message(DEBUG " using git submodule for nlohmann JSON")
    set(JSON_BuildTests OFF CACHE INTERNAL "")
    add_subdirectory(nlohmann_json)
endif()
```
and `CMakeLists.txt`:
``` cmake
option(USE_EXTERNAL_JSON "Use an external nlohmann JSON library" ON)
# ...
add_subdirectory(extern)
# ...
target_link_libraries(${MY_TARGET} PRIVATE "nlohmann_json::nlohmann_json")
```
I get an error:
```
  Target "MyTarget" links to target "nlohmann_json::nlohmann_json" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
```
However, when removing the namespace:
``` cmake
# ...
target_link_libraries(${MY_TARGET} PRIVATE "nlohmann_json")
```
Configure throws no error, but now build cannot find the header.
```
fatal error: 'nlohmann/json.hpp' file not found
#include <nlohmann/json.hpp>
         ^~~~~~~~~~~~~~~~~~~
```
### Describe which system (OS, compiler) you are using.

macOS 10.14.6
CMake 3.14.5

Homebrew
```
$ brew --version
Homebrew 2.1.11
Homebrew/homebrew-core (git revision ab0ed; last commit 2019-10-02)
Homebrew/homebrew-cask (git revision ccc697; last commit 2019-10-02)
```
### Describe which version of the library you are using.

nlohmann_json
```
$ brew info nlohmann-json
nlohmann-json: stable 3.7.0 (bottled), HEAD
JSON for modern C++
https://github.com/nlohmann/json
/usr/local/Cellar/nlohmann-json/3.7.0 (8 files, 1MB) *
  Poured from bottle on 2019-09-26 at 17:09:43
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/nlohmann-json.rb
==> Dependencies
Build: cmake ✘
==> Options
--HEAD
	Install HEAD version
```

[1]: https://github.com/nlohmann/json#supporting-both
[2]: https://github.com/nlohmann/json#external

**Comment by martin-schulze-vireso** [comment]
Just in case someone stumbles upon this as I did:
I saw the exact same symptoms in an android build where a gradle project pulled in my own library via externalNativeBuild that in turn should pull in this library via `add_subdirectory`.

It turned out that I confused myself with the hierarchy of my larger project and only built the part of my CMake project tree which did not contain the `add_subdirectory` for this library. (Part of) my rough project layout:
```
parent/
  CMakeLists.txt
  third_party/nlohman_json/
   ...
   CMakeLists.txt
  my_library/
    CMakeLists.txt
```
The `add_subdirectory(third_party/nlohmann_json)` was done in `parent/CMakeLists.txt` but gradle ran cmake only on `my_library/CMakeLists.txt`, so it never saw that. After moving `add_subdirectory(../third_part/nlohmann_json ${CMAKE_CURRENT_BINARY_DIR)/nlohmann_json)` into `my_library/CMakeLists.txt` it worked as expected.
