### ISSUE TITLE
Problems with special German letters

### ISSUE THREAD

**Issue by KeksMeister** [nlohmann/json#1789]
Hi,

I have some problems with reading letters like Ä, Ü, Ö,... from a JSON file.
In my JSON file there is (besides a lot of other data):

`{
    "Szene_3": [
        {
            [...]
            "Header": {
                [...]
                "Text": "Bücher"
            }
        }
    ]
}`

When I read this (jsonFile being of type json and i being an int)

```
std::ifstream inStream("config.json");
nlohmann::json jsonFile;
inStream >> jsonFile;
[...]
for (int i = 0; i < size; i++) {
    std::string header = jsonFile["Szene_3"][i]["Header"]["Text"];
    [...]
}
```

I get "BÃ¼cher" in the string. When I write this exact string back into my json File it becomes "Bücher" again, yet I need to display the correct string in my application.

Can please somebody help me with this?

**Comment by nlohmann** [comment]
In order to asses your issue, we need the following information:

- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by nlohmann** [comment]
(Just a note: the library only supports UTF-8.)
