### ISSUE TITLE
conflit with g++ compile option -mwindows

### ISSUE THREAD

**Issue by liufanghua2012** [nlohmann/json#1860]
- What is the issue you have?
i found json.hpp conflicted with g++ build option -mwindows. When the option -mwindows was used, although the build succeeded, the exe file could not start normally. The program exited with an error code of 0xc000007b. 

when i removed the option -mwindows, everything is ok.

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by nlohmann** [comment]
In order to asses your issue, we need the following information:

- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by liufanghua2012** [comment]
I am sorry, it might be my own mistakes. i will check again and feedback later. Thanks for your response:)

**Comment by ticodevv** [comment]
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/341b52c0-768d-40c1-b077-af042de21c79">
do you have solution ? 

i've tried to replace ca part ca ca doesn't work i'm out of ideas
<img width="617" alt="image" src="https://github.com/user-attachments/assets/85792e2e-6549-4ab7-ac07-4f0873259e2d">
--> 
<img width="582" alt="image" src="https://github.com/user-attachments/assets/8c3dbc0e-d7de-42d5-8474-891a2ffc1f0f">
doesn't work
