### ISSUE TITLE
Struct with array of struct and __attribute__((packed))

### ISSUE THREAD

**Issue by wiesener** [nlohmann/json#1866]
What is the issue you have?

"cannot bind packed field".

Please describe the steps to reproduce the issue. Can you provide a small but working code example?

I've tried to cast a json dataset to a custom struct which is attribute packed and includes an array of type enum and an array of structs.

What is the expected behavior?

That it should cast the dataset with the given to_json and from_json functions.

And what is the actual behavior instead?

It does not compile with the following errors:

../src/main.cpp:37:23: error: cannot bind packed field ‘p.data_t::dur’ to ‘unsigned int&’
../src/main.cpp:38:23: error: cannot bind packed field ‘p.data_t::seq’ to ‘unsigned int&’
../src/main.cpp:39:24: error: cannot bind packed field ‘p.data_t::mode’ to ‘unsigned int (&)[5]’
../src/main.cpp:40:26: error: no matching function for call to ‘nlohmann::basic_json<>::get_to(internal_data_t [2]) const’

json.hpp:17270:25: error: no type named ‘type’ in ‘struct std::enable_if<false, int>’ 
json.hpp:17282:72: error: no type named ‘type’ in ‘struct std::enable_if<false, int>’
....

Which compiler and operating system are you using? Is it a supported compiler?
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

Did you use a released version of the library or the version from the develop branch?
released

If you experience a compilation error: can you compile and run the unit tests?
Yes the unit tests run fine.

Minimal example:

main.cpp:

```
// json handling
#include <iostream>

#include <stdint.h>

typedef struct __attribute__((packed)){
uint8_t nop;
uint16_t start[5];
uint16_t end[5];
} internal_data_t;

typedef enum __attribute__((packed)){
	FOOBAR = 0,
	BAZ = 1
} foo_t;

typedef struct __attribute__((packed)){
uint32_t dur;
uint32_t seq;
mode_t mode[5];
internal_data_t dat[2];
} data_t;

#include <fstream>
#include "json.hpp"

using namespace std;

void to_json(json& j, const data_t& p) {
	j = json{{"dur", p.dur}, {"seq", p.seq},
		{"mode", p.mode}, {"dat", p.dat}
	};
}

void from_json(const json& j, data_t& p) {
	j.at("dur").get_to(p.dur);
	j.at("seq").get_to(p.seq);
	j.at("mode").get_to(p.mode);
	j.at("dat").get_to(p.dat);
}


int main(int argc, char **argv)
{
	// Stimulator is connected but not idle
	std::ifstream file("test.json");
	json dat_json;
	file >> dat_json;
	std::cout << dat_json << std::endl;

	auto dat = dat_json.get<data_t>();

    return 0;
}
```

test.json:
```
{
"dur": 36000,
"seq": 1000,
"mode": [83, 83, 83, 83, 0],
"dat": [
{
"nop": 1,
"start": [150, 0, 0, 0, 0],
"end": [300, 0, 0, 0, 0]
},
{
"nop": 1,
"start": [150, 0, 0, 0, 0],
"end": [300, 0, 0, 0, 0]
}
]
}
```

**Comment by nlohmann** [comment]
In order to asses your issue, we need the following information:

- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by nickaein** [comment]
> ../src/main.cpp:37:23: error: cannot bind packed field ‘p.data_t::dur’ to ‘unsigned int&’

The _cannot bind packed field_ errors occurs since [`get_to()`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a65753c68f06639eda0d355f919564e01.html#a65753c68f06639eda0d355f919564e01) accepts an l-value reference but you cannot get a reference to objects with alignment requirements ([more info](https://stackoverflow.com/a/29342850/161640)). 

One solution is to use [`get<T>()`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_aa6602bb24022183ab989439e19345d08.html#aa6602bb24022183ab989439e19345d08) and assignment:

```
p.dur = j.at("dur").get<uint32_t>();
p.seq = j.at("seq").get<uint32_t>();
...
```

> ../src/main.cpp:40:26: error: no matching function for call to ‘nlohmann::basic_json<>::get_to(internal_data_t [2]) const’

You also need to provide a `to_json()` implementation for `internal_data_t` type so that the library knows how to convert `data_t::dat` field (which is of type `internal_data_t`) into JSON object.

**Comment by wiesener** [comment]
Thanks for the hint. I've changed it but still getting errors:```


void to_json(json& j, const data_t& p) {
	j = json{{"dur", p.dur}, {"seq", p.seq},
		{"mode", p.mode}, {"dat", p.dat}
	};
}

void to_json(json& j, const internal_data_t& p) {
	j = json{{"nop", p.nop}, {"start", p.start},
		{"end", p.end}
	};
}


void from_json(const json& j, data_t& p) {
	p.dur = j.at("dur").get<uint32_t>();
	p.seq = j.at("seq").get<uint32_t>();
	p.mode = j.at("mode").get<mode_t>();
	p.dat = j.at("dat").get<internal_data_t>();
}
```

Error message:
../src/main.cpp:45:36: error: incompatible types in assignment of ‘unsigned int’ to ‘mode_t [5] {aka unsigned int [5]}’
  p.mode = j.at("mode").get<mode_t>();
                                    ^
../src/main.cpp:46:43: error: no matching function for call to ‘nlohmann::basic_json<>::get<internal_data_t>() const’
  p.dat = j.at("dat").get<internal_data_t>();

and:
error: no type named ‘type’ in ‘struct std::enable_if<false, int>’

I guess there is something missing to tell the compiler that it is an array.

**Comment by nickaein** [comment]
For arrays, the library accepts `T = std::vector<T>` type for `get<T>()`. I doubt the fixed-size arrays are supported given that JSON only supports variable-length arrays. Also given that the arrays are packed too, I believe the only way to use an intermediate `std::vector` object, e.g.:

```cpp
    auto mode_vec = j.at("mode").get<std::vector<mode_t>>();
    for(size_t i=0; i<mode_vec.size(); i++)
    {
        p.mode[i] = mode_vec[i];
    }
```

Here is a minimal working code: https://wandbox.org/permlink/cj2Mn1k6dKnjrxch
