### ISSUE TITLE
null strings

### ISSUE THREAD

**Issue by ETLang** [nlohmann/json#1867]
The following is valid JSON that fails to parse as a string:

{ "name" : null }

**Comment by t-b** [comment]
My application based on this library can parse it. Are you sure? What is the error message?

**Comment by nlohmann** [comment]
In order to asses your issue, we need the following information:

- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by ETLang** [comment]
I'm using the single-include json.hpp, version 3.7.3.

Test case:
        std::string testJson = "{ \"name\" : null }";
        auto j = json::parse(testJson);
        auto parsed = j.at("name").get<std::string>();

Actual Result:
  Exception with message '[json.exception.type_error.302] type must be string, but is null'

Expected Result: 
  Tricky because std::string has no concept of null, but JSON strings definitely do. Maybe there's a way to manage this that I'm missing? My expectation is that null strings be translated into empty ones, but I can understand this not being universally preferable. Setting a flag on the parser could do the trick.

**Comment by ETLang** [comment]
Nevermind, I'm dumb. I just added a is_null() check before parsing that field.
