### ISSUE TITLE
Watch JSON variables in Debug

### ISSUE THREAD

**Issue by csurgay** [nlohmann/json#1902]
Hi All,
is there a way to watch JSON variable values in Debug/Watch list in IDEs?
Regards, Peter

**Comment by dota17** [comment]
Hmmmm, I run and debug in Clion, but i can't watch Json variable values too.
It shown that command time out.

![image](https://user-images.githubusercontent.com/50514813/72510164-e578ec80-3883-11ea-95be-603403dcdfc7.png)

But all is ok in VS.

**Comment by nickaein** [comment]
Relevant: https://github.com/nlohmann/json/issues/1554

**Comment by dota17** [comment]
Still fail in Clion, and this time i got `cannot access memory`.
![image](https://user-images.githubusercontent.com/50514813/76505717-e47bca00-6484-11ea-8912-0e45fdecaba2.png)

`res` is a array-type json, and i push back 3 object items.
Using `p res` in gdb, i got 
```
$1 = {m_type = nlohmann::detail::value_t::array, m_value = {object = 0x1048060<error reading variable: Cannot access memory at address 0xabababb7>, array = 0x1048060 = {[0] = {m_type = nlohmann::detail::value_t::object, m_value = {object = 0x10480b0 = {[0] = "age", [1] = {m_type = 
....
```
I think the print message in gdb is OK.
Maybe Clion just get the first `error reading variable: Cannot access memory at address 0xabababb7` so that it fails in Clion. If so, the probleam could be from Clion.

But when i print the first item by `p res[0]`, i got `Segmentation fault`.

**Comment by nlohmann** [comment]
Related: #1952
