### ISSUE TITLE
This i can write and read any file thanks

### ISSUE THREAD

**Issue by aurea1123** [nlohmann/json#1927]
- Describe what you want to achieve.

- Describe what you tried.

- Describe which system (OS, compiler) you are using.

- Describe which version of the library you are using (release version, develop branch).

**Comment by nlohmann** [comment]
In order to asses your issue, we need the following information:

- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?
