### ISSUE TITLE
Where is the library built and what is the name?

### ISSUE THREAD

**Issue by coderDec** [nlohmann/json#1977]
- Describe what you want to achieve.
I see that the documentation mentions "

> To use this library from a CMake project, you can locate it directly with find_package()
however, when I build the project, I do not see any library built. 

- Describe what you tried.
History of commands
`
 2074  git clone https://github.com/nlohmann/json.git
 2075  git branch
 2076  ls
 2077  cd json/
 2078  git branch
 2079  git pull
 2080  ls
 2081  vi CODE_OF_CONDUCT.md 
 2082  mkdir build
 2083  cd build/
 2084  ls
 2085  cmake ..
 2086  cmake --build .
 2087  ctest --output-on-failure
`
- Describe which system (OS, compiler) you are using.
find . -name "lib*"
./CMakeFiles/Export/lib
./test/cmake_add_subdirectory/nlohmann_json/CMakeFiles/Export/lib

and in these locations, it is not the library.

- Describe which version of the library you are using (release version, develop branch).
develop branch

**Comment by nickaein** [comment]
As mentioned in [README](https://github.com/nlohmann/json#integration), this is single-header library and there is no need to build anything. Just add the provided `json.hpp` to your project and you are good to go.

**Comment by coderDec** [comment]
@nickaein if I want to use it as an external component to my project. What is the suggestion?

**Comment by coderDec** [comment]
I also tried this : https://github.com/nlohmann/json/issues/1976#issuecomment-597960625

It still fails

**Comment by nlohmann** [comment]
In order to asses your issue, we need the following information:

- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by ArtemSarmini** [comment]
@coderDec cmake integration is described here https://github.com/nlohmann/json#cmake. You may add `PATHS <path_to_json>` argument to `find_package` if path os non-default.
