### ISSUE TITLE
how use   template <typename T> struct adl_serializer 

### ISSUE THREAD

**Issue by wuvalue** [nlohmann/json#2035]
-
template <typename T>
struct adl_serializer {
    static void to_json(json& j, const T& value) {
        // calls the "to_json" method in T's namespace
    }

    static void from_json(const json& j, T& value) {
        // same thing, but with the "from_json" method
    }
};

**Comment by nlohmann** [comment]
In order to asses your issue, we need the following information:

- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by ArtemSarmini** [comment]
You specialize adl_serializer in nlohmann namespase for your types. Example is here https://github.com/nlohmann/json/blob/develop/README.md#arbitrary-types-conversions.

**Comment by nlohmann** [comment]
@wuvalue Do you need further assistance?
