### ISSUE TITLE
iterator based erase method

### ISSUE THREAD

**Issue by dpellegr** [nlohmann/json#2122]
Hello, I was wondering if you could consider adding the iterator based erase method, with exactly the same specifications as `std::vector`: https://en.cppreference.com/w/cpp/container/vector/erase 
Not having it is not at all a deal breaking, but it comes handy from times to times. Thank you!

**Comment by nlohmann** [comment]
This is done since version 1.0.0:

<img width="601" alt="image" src="https://user-images.githubusercontent.com/159488/82211454-24da4700-9911-11ea-9d94-15c559e3fada.png">

See https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a068a16e76be178e83da6a192916923ed.html#a068a16e76be178e83da6a192916923ed and https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a4b3f7eb2d4625d95a51fbbdceb7c5f39.html#a4b3f7eb2d4625d95a51fbbdceb7c5f39 for more information.
