### ISSUE TITLE
Access keys when iteration with new for loop C++11

### ISSUE THREAD

**Issue by mdickie** [nlohmann/json#256]
Here is an example where you can access the values of the json object. However, I have no idea to access the keys.
``` C++
using json = nlohmann::json;
int main() {
    json j = {
        {"name", "John Doe"},
        {"born", "xxxx"}
    };
    for (auto& element: j) {
        std::cout << element << std::endl;
    }
}
```
Here is working example with stl where it is possible to access the keys:
``` C++
#include <iostream>
#include <map>

using std::string;

int main() {
    std::map<string, string> m = {
        {"name", "Mariusz Wojcik"},
        {"born", "1997"}
    };
    for (std::pair<string, string> p: m) {
        std::cout << std::get<0>(p) << ": " << std::get<1>(p) << std::endl;
    }
}
```
So there is my question: Is it possible to access these keys with json in a similiar way?

**Comment by nlohmann** [comment]
Hi @mdickie,

if you iterate explicitly via `for (auto it = j.begin(); it != j.end(); ++j)` you can use `j.key()` and `j.value()` to access the object's key and value, respectively. For range for, this is not possible, because the `value_type` of a `json` object is `json` itself and not something like `std::pair`. To overcome this, there exists an [`iterator_wrapper`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_ab936779c70bec68343ef440ed13251e5.html#ab936779c70bec68343ef440ed13251e5) that provides an adapter that you can use like this:

```cpp
for (auto& element : json::iterator_wrapper(j))
{
  std::cout << element.key() << " maps to " << element.value() << std::endl;
}
```

Note that the name of this function may change in the future - when I introduced it, it seemed as if people agreed that they did not like the name, but did not propose something better 😄. So if you have an idea, I'm all ears!

**Comment by qis** [comment]
I would propose the name "object_iterator" which more closely resembles [std::filesystem::directory_iterator](http://en.cppreference.com/w/cpp/experimental/fs/directory_iterator).

**Comment by nlohmann** [comment]
@qis Thanks for the hint! I'll also see whether I can find some inspiration there.

@mdickie Did https://github.com/nlohmann/json/issues/256#issuecomment-223083274 solve your problem?

**Comment by mdickie** [comment]
@nlohmann Yeah, thanks

**Comment by nlohmann** [comment]
I close this issue. I'm still happy for any comments regarding the name of the `iterator_wrapper`.

**Comment by cezheng** [comment]
just to share how Swift name it when using `for ... in` to iterate the objects in an array with relevant indexes

```swift
let a = ["a", "b","c"]
for (index, item) in a.enumerated() {
  // ...
}
```

it may look nicer if we define `json::iterator_wrapper` as a member function of json, like this

```cpp
json j = {{"a", 1}, {"b", 2}, {"c", 3}};
for (auto& entry : j.object_iterator()) {
  // entry.key();
  // entry.value();
  // ...
}
```

**Comment by qis** [comment]
I would expect `json::object_iterator` to be a type and not a function.

**Comment by nlohmann** [comment]
Yes, the `()` looks weird in this setting.

I like Python's [`items()`](https://docs.python.org/2/library/stdtypes.html#dict.items) member function:

> Returns the element attributes as a sequence of `(name, value)` pairs. The attributes are returned in an arbitrary order.

(in fact documentation from [xml.etree.ElementTree.items()](https://docs.python.org/3.1/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element.items))
