### ISSUE TITLE
Critical error detected c0000374 on windows10 msvc 2019 16.8.5

### ISSUE THREAD

**Issue by alanyangbo** [nlohmann/json#2710]
![bug](https://user-images.githubusercontent.com/8469922/114333098-1bd21400-9b7a-11eb-99cc-fc8181fec95c.PNG)
![bug1](https://user-images.githubusercontent.com/8469922/114333310-93a03e80-9b7a-11eb-9949-9e7269b72589.PNG)

**Comment by nlohmann** [comment]
In order to asses your issue, we need the following information:

- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?
