### ISSUE TITLE
Deadlock on create json - windows only

### ISSUE THREAD

**Issue by gabrielOttopia** [nlohmann/json#3129]
I am creating a json object that has both nested and non nested fields ie.

```
nlohmann::json j;
j["first"] = "something";
j["second"]["more"] = "something_else";
```

If i create this object, the program gets stuck/in a deadlock. If i reverse the order so that the simple object is after the nested, there is no deadlock.

My solution was: 

```
nlohmann::json j;
j["second"]["more"] = "something_else";
j["first"] = "something";

```

This was only reproduced on windows, did not occur in linux.

**Comment by nlohmann** [comment]
In order to asses your issue, we need the following information:

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by nlohmann** [comment]
@gabrielOttopia Can you please provide more information on the issue?
