### ISSUE TITLE
Not able to use nlohmann json with c++ code built using emscripten to wasm

### ISSUE THREAD

**Issue by aykejriw-ms** [nlohmann/json#3200]
I am getting errors in json::parse when i am using json::parse code in my c++ and compiling that to wasm.

**Comment by nlohmann** [comment]
In order to asses your issue, we need the following information:

- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by gregmarr** [comment]
FYI, we have been using this library in WASM through Emscripten for several years with no issues.

**Comment by aykejriw-ms** [comment]
Closing the issue , will raise another with more information
