### ISSUE TITLE
includedir in pkgconfig is error if install_headers() has subdir argument. 

### ISSUE THREAD

**Issue by hlqqlm** [nlohmann/json#3284]
meson.build has below code:
  install_headers('single_include/nlohmann/json.hpp',  subdir: 'nlohmann')
It install header file into subdir, such as
  ~/.local/nlohmann

but pkgconfig file nlohmann_json.pc has below code:
  includedir=${prefix}/include
It should be:
  includedir=${prefix}/include/nlohmann

You can fix this bug by installing header without subdir:
  install_headers('single_include/nlohmann/json.hpp')
Otherwise you can change pkgconfig file nlohmann_json.pc, but I don't know how to do that.

**Comment by nlohmann** [comment]
Is this related to #3248?

**Comment by eli-schwartz** [comment]
This seems to be incorrect, because as per the documentation at https://github.com/nlohmann/json#integration you should be using:

```c
#include <nlohmann/json.hpp>
```

and as such, it is correct to install it to an "nlohmann/" subdirectory but not add that to the include paths.

Conversely, you appear to instead be using:

```c
#include <json.hpp>
```

Which is a bad idea for several reasons -- scoping, particularly, because it's hardly as though "json.hpp" is an uncommon header name. And indeed, if you use this then it will not be found in `${prefix}/include`.

If you use the cmake config files instead of the pkg-config files, you will still get `${prefix}/include`, not `${prefix}/include/nlohmann/`, so it is not a pkg-config issue either. Nor is it anything to do with meson, because cmake also installs a pkg-config file, and that pkg-config file points to the same path (`${prefix}/include`) that meson's generated pkg-config file uses.

**Comment by gregmarr** [comment]
@eli-schwartz is correct.  It is expected that `nlohmann/` be part of your `#include`.  It doesn't make a lot of difference if you install the single include header and decide to put `nlohmann` in your include path and do the include without it, but it's mandatory that you use the expected form if you use the multiple headers, as they include each other using the `#include <nlohmann/...>` form.  For that reason, it's best to always include it with the `nlohmann/` prefix and have the `nlohmann` directory inside a directory in your include path.

**Comment by nlohmann** [comment]
Anything to do here?

**Comment by hlqqlm** [comment]
@eli-schwartz is correct. We should code as below:
#include <nlohmann/json.hpp>
