### ISSUE TITLE
when i use it in C++ sserver,it it constantly show that fatal error: adl_serializer.hpp: No such file or directory

### ISSUE THREAD

**Issue by kevenlau** [nlohmann/json#3404]
when i see this error,i change my path.but it never works.it showed a similar issue.

**Comment by nlohmann** [comment]
In order to asses your issue, we need the following information:

- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by nlohmann** [comment]
@kevenlau Can you please provide more information on the issue?
