### ISSUE TITLE
Floating point precision lost

### ISSUE THREAD

**Issue by nickvkaam** [nlohmann/json#345]
Input:

```
json data;
data["number"] = 11.4f;
```

output:

`std::string dataString = data.dump();`

result:

```
{
    "number": 11.3999996185303
}
```

**Comment by FabianoGK** [comment]
That is because you cannot represent 11.4 as a single-precision floating-point number. Take a look into [ExploringBinary - Floating Point Converter](http://www.exploringbinary.com/floating-point-converter/).

Here is an example having the literal number on different precisions:

Input:
```c
json data;
data["number-float"] = 11.4f;
data["number-double"] = 11.4;
data["number-long-double"] = 11.4l;
```

Output:
```c
std::string dataString = data.dump();
```

Result:
```json
{
    "number-double":11.4,
    "number-float":11.3999996185303,
    "number-long-double":11.4
}
```

**Comment by phoenixchinar** [comment]
You need to use decimal floating point to solve this issue. Normal float, double, and long double are based on a base of 2 and cannot represent all base 10 floating point numbers accurately. gcc has decimal32, decimal64 and decimal128 classes as well as underlying C types defined to address this.
In your compiler try this
if((0.1+0.2)==0.3) 
   std::cout<<"true"<<endl; 
else 
   std::cout<<"false"<<endl;

You will need to change the underlying types, as the library serializes the underlying types accurately.

**Comment by nlohmann** [comment]
Can this ticket be closed?
