### ISSUE TITLE
class-level enum not serialized as string via NLOHMANN_JSON_SERIALIZE_ENUM

### ISSUE THREAD

**Issue by nicsav** [nlohmann/json#3715]
### Description

If I have a class-level 'enum class' then is seems that NLOHMANN_JSON_SERIALIZE_ENUM has no effect (i.e. it's values are still serialized as integers).

 

### Reproduction steps

compile and run the code example

### Expected vs. actual results

[
  [],
  {
    "ie": "bar",
    "oe": "foo"
  }
]

vs 

[
  [],
  {
    "ie": 1,
    "oe": "foo"
  }
]

### Minimal code example

```Shell
#include <iostream>
#include "json.hpp"

enum class OutEnum { FOO, BAR };

NLOHMANN_JSON_SERIALIZE_ENUM(OutEnum, {
                                          {OutEnum::FOO, "foo"},
                                          {OutEnum::BAR, "bar"}
                                      })

class C {
 public:
  enum class InEnum { FOO, BAR };

  NLOHMANN_JSON_SERIALIZE_ENUM(InEnum,
                               {
                                {InEnum::FOO, "foo"},
                                {InEnum::BAR, "bar"}
                                })

  OutEnum oe{OutEnum::FOO};
  InEnum ie{InEnum::BAR};

  NLOHMANN_DEFINE_TYPE_INTRUSIVE(C, oe, ie)
};

int main() {
    C c;
    nlohmann::json json { nlohmann::json::array() };
    json += c;
    std::cout << json.dump(2) << std::endl;
    return 0;
}
```

### Error messages

```Shell
n/a
```

### Compiler and operating system

Ubuntu 20.04.4 LTS + gcc version 9.4.0

### Library version

3.11.2

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by falbrechtskirchinger** [comment]
By putting the macro inside the class, you're defining the serialization functions inside the class body, which obviously doesn't work.

```cpp
class C {
   public:
    enum class InEnum { FOO, BAR };

    OutEnum oe{OutEnum::FOO};
    InEnum ie{InEnum::BAR};

    NLOHMANN_DEFINE_TYPE_INTRUSIVE(C, oe, ie)
};

NLOHMANN_JSON_SERIALIZE_ENUM(C::InEnum,
                             {{C::InEnum::FOO, "foo"}, {C::InEnum::BAR, "bar"}})
```

Using the macro as intended (i.e., in namespace scope) works just fine.

**Comment by nicsav** [comment]
Works as expected.

**Comment by lucidBrot** [comment]
Maybe "works as expected" but is not clear from the docs.

I just ran into the same problem with an `enum class` inside a `struct`. The [documentation](https://json.nlohmann.me/api/macros/nlohmann_json_serialize_enum/#notes) has a few notes, including  

> The macro must be used inside the namespace of the enum.

But that was fulfilled.
I figured out how to do this now, thanks to this issue. Adding my thoughts as bullet points:


* I think it would help if there was another note for this, that says something like  

  > The macro may not be put inside a class or struct.

  However even with that note, I (aka the dumbest expected user), would have thought it means that I must move the `enum class` outside of the struct as well, so that the macro and enum are used in the same scope.

* Would it perhaps be possible to add @falbrechtskirchinger 's [above example](https://github.com/nlohmann/json/issues/3715#issuecomment-1231139786) as an example to the documentation's [example section](https://json.nlohmann.me/api/macros/nlohmann_json_serialize_enum/#examples)?


* > By putting the macro inside the class, you're defining the serialization functions inside the class body, which obviously doesn't work.   

  I have no idea how hard this is, but would it be possible to print a warning or cause an error when someone misuses the macro like this?
