### ISSUE TITLE
double free or Assertion failed!

### ISSUE THREAD

**Issue by caogenwang** [nlohmann/json#3729]
### Description

void nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, 
 NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::assert_invariant() const 
 [with ObjectType = std::map; ArrayType = std::vector; StringType = std::__cxx11::basic_string<char>; 
 BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; 
 NumberFloatType = double; AllocatorType = std::allocator; JSONSerializer = nlohmann::adl_serializer]: 
 Assertion `m_type != value_t::object || m_value.object != nullptr' failed.

### Reproduction steps

void nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, 
 NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::assert_invariant() const 
 [with ObjectType = std::map; ArrayType = std::vector; StringType = std::__cxx11::basic_string<char>; 
 BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; 
 NumberFloatType = double; AllocatorType = std::allocator; JSONSerializer = nlohmann::adl_serializer]: 
 Assertion `m_type != value_t::object || m_value.object != nullptr' failed.

### Expected vs. actual results

void nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, 
 NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::assert_invariant() const 
 [with ObjectType = std::map; ArrayType = std::vector; StringType = std::__cxx11::basic_string<char>; 
 BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; 
 NumberFloatType = double; AllocatorType = std::allocator; JSONSerializer = nlohmann::adl_serializer]: 
 Assertion `m_type != value_t::object || m_value.object != nullptr' failed.

### Compiler and operating system

linux

### Library version

version 2.1.1

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
In order to asses your issue, we need the following information:

- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by caogenwang** [comment]
I am so sorry that it's our mistake!It's not the fault of library.we did not have a mutex lock in mutiple threads environment.Thanks for replaing.
