### ISSUE TITLE
[json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal

### ISSUE THREAD

**Issue by yangkangdev** [nlohmann/json#3882]
### Description

Hey, I found a strange bug.  The same code, same json, windows is normal, mac is unnormal. 
When my code runs on the macos, print this error info.
`libc++abi: terminating with uncaught exception of type nlohmann::json_abi_v3_11_2::detail::parse_error: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal`

So, I tried to modify json data, then this error disappeared. I found this library can't parse this json data.
`"channels": [
                "L",
                "A"
            ]`

The whole json data is below.
`{
    "Data/Images/AmberLogo.png": {
        "props": {
            "comression": "LowCompress",
            "usage": "sRGB",
            "mipmap": "Off",
            "premul": "Premul"
        },
        "prop_raw_info": "-s_-p_",
        "size": {
            "width": 1024,
            "height": 256,
            "raw_size": 9.291,
            "channels": [
                "L",
                "A"
            ],
            "comp_astc_size": 256.215,
            "comp_etc_size": 256.215
        }
    }
}`

### Reproduction steps

As desc.

### Expected vs. actual results

solve this bug。

### Compiler and operating system

Mac & AppleClang

### Library version

3.11.2

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
The error message usually means that the file could not be opened. Please check if you can print the file content without the library. Maybe a path was not set correctly.

**Comment by gregmarr** [comment]
> So, I tried to modify json data, then this error disappeared. I found this library can't parse this json data.
```"channels": [ "L", "A" ]```

That's correct, this isn't valid JSON.  You need the outer `{}`.

```{ "channels": [ "L", "A" ] }```

**Comment by yangkangdev** [comment]
I am very sorry to reply to you so late because I am ill. I tried to load this data to string and succeed to print it. As my this bug desc, error info be print when I tried to parse the array data ("channels": [ "L", "A" ]).

**Comment by nlohmann** [comment]
I need a code example.

**Comment by yangkangdev** [comment]
I test my data using the latest version on my MacBook, everything is ok. I need more tests for my case. Thank you for you pay attention to this issue.

```
json json_obj = json::parse(R"(
{
    "Data/Images/AmberLogo.png": {
        "props": {
            "comression": "LowCompress",
            "usage": "sRGB",
            "mipmap": "Off",
            "premul": "Premul"
        },
        "prop_raw_info": "-s_-p_",
        "size": {
            "width": 1024,
            "height": 256,
            "raw_size": 9.291,
            "channels": [
                "L",
                "A"
            ],
            "comp_astc_size": 256.215,
            "comp_etc_size": 256.215
        }
    }
}
)");

for (auto it = json_obj.begin(); it != json_obj.end(); it++) {
	auto info_value = it.value();
	auto size_info = info_value.at("size").get<json>();
	
	std::cout << size_info["width"].get<int>() << std::endl;
	std::cout << size_info["height"].get<int>() << std::endl;
	
	// Print error info in this line, but now, everything is ok.
	auto channels = size_info["channels"].get<std::vector<std::string>>();
	for (auto &channel : channels) {
	  std::cout << channel << std::endl;
	}
}
```

**Comment by yonghenghuanmie** [comment]
> I need a code example.  

I had the same problem.
When I run this code
```
nlohmann::json data = R"(
	{"params": { "message_id": "参数值" }}
)"_json;
```
It will throw an exception told me parse error.
json: 3.11.2, compiler: msvc 17.5 preview

**Comment by nlohmann** [comment]
What is the exact message?

**Comment by yonghenghuanmie** [comment]
> What is the exact message?

"0x00007FF9568D428C 处(位于 cqhttp.exe 中)有未经处理的异常: Microsoft C++ 异常: nlohmann::json_abi_v3_11_2::detail::parse_error，位于内存位置 0x000000076EBCE4A0 处。"

CallStack: https://drive.google.com/file/d/1O2ZNxY5JAQH6UFZrb0291uGt0fc7AwK8/view?usp=sharing

**Comment by nlohmann** [comment]
Can you catch the exception and print the what() message?

**Comment by yonghenghuanmie** [comment]
[json.exception.parse_error.101] parse error at line 2, column 30: syntax error while parsing value - invalid string: ill-formed UTF-8 byte; last read: '"?

**Comment by nlohmann** [comment]
Then your input is not UTF-8. See https://json.nlohmann.me/home/faq/#parse-errors-reading-non-ascii-characters

**Comment by Keyunge** [comment]
Hi, had this error: `[json.exception.parse_error.101] parse error at line 1, column 440: syntax error while parsing value - unexpected '{'; expected end of input`

And have this json data: `{"latitude":47.0,"longitude":142.75,"generationtime_ms":0.051021575927734375,"utc_offset_seconds":0,"timezone":"GMT","timezone_abbreviation":"GMT","elevation":47.0,"current_units":{"time":"iso8601","interval":"seconds","temperature_2m":"°C","relative_humidity_2m":"%","is_day":"","wind_speed_10m":"km/h"},"current":{"time":"2026-01-08T04:30","interval":900,"temperature_2m":-10.0,"relative_humidity_2m":73,"is_day":1,"wind_speed_10m":15.1}}`

Here is my code, if you need it : 
```   
   auto fullJson = json::parse(raw_data);
   auto c = fullJson.at("current");
   
    CurrentWeather current;
    current.time = c.at("time").get<std::string>();
    current.temperature = c.at("temperature_2m").get<double>();
    current.humidity = c.at("relative_humidity_2m").get<int>();
    current.is_day = c.at("is_day").get<int>() == 1; // Convert 1/0 to bool
    current.wind_speed = c.at("wind_speed_10m").get<double>();

    return current;
````
and 
```
    try
    {
        CurrentWeather weather = GetWeatcher();

        std::cout << "Temperature: " << weather.temperature << "°C" << std::endl;
        std::cout << "Humidity:    " << weather.humidity << "%" << std::endl;
        std::cout << "Now:         " << (weather.is_day ? "Day" : "Night") << std::endl;
        std::cout << "Wind Speed:  " << weather.wind_speed << " m/s" << std::endl;
    }
    catch (const std::exception &e)
    {
        std::cerr << "\e[0;31m JSON ERROR \e[0;37m " << e.what() << std::endl;
        return 1;
    }
```

If i'm stupid, just say me it :з

**Comment by nlohmann** [comment]
@Keyunge Can you make sure the input is properly terminated? What do you pass to `parse` - a `const char*`?

**Comment by gregmarr** [comment]
Column 440 of that data is not `{`, so there must be a difference between what you think you are parsing and what you are actually parsing.

**Comment by Florida-Rob** [comment]
for those if using esp-idf (5+), registering here what the solution was:
Bug #1: The "Ghost S" Discovery Glitch
The Problem: xLights discovery would fail or show the controller as "Unknown." Wireshark showed that xLights was sometimes "eating" or corrupting the first byte of the WebSocket text frame, turning {"system"... into s"ystem"....

The File: main/unified_server.c (or wherever your DEVICE_CONFIG_JSON is defined).

The Change:
Add "sacrificial" padding to the start of your JSON string.
`// BEFORE: 
static const char* DEVICE_CONFIG_JSON = "{\"system\":{\"product\":\"ESPixelStick\"}...";

// AFTER (The Fix): 
// Two leading spaces ensure the '{' remains the start of the object if bytes are dropped.
static const char* DEVICE_CONFIG_JSON = "  {\"system\":{\"product\":\"ESPixelStick\"}...";`

Why it works: By prepending non-functional whitespace, we provide a "buffer zone." The JSON parser ignores the leading spaces, so the payload remains valid even if xLights mishandles the start of the frame.

Bug #2: The WebSocket "Burst" Crash
The Problem: During an "Upload to Controller" or rapid discovery, the ESP32-C6 would crash with a LoadProhibited error or a Task Watchdog Timeout. This happened because xLights spams G1 and G2 (status/config) requests so fast that the CPU never leaves the WebSocket handler.

The File: main/unified_server.c (inside your xlights_ws_handler function).

The Change:
Force a task yield at the end of the WebSocket callback.
`static esp_err_t xlights_ws_handler(httpd_req_t *req) {
    // ... (existing logic to receive and send frames) ...

    // THE FIX:
    // Force the task to yield for 1 tick (usually 1ms to 10ms depending on config)
    vTaskDelay(pdMS_TO_TICKS(1)); 

    return ESP_OK;
}`
Why it works: In ESP-IDF, the HTTP server runs in its own task. If a WebSocket handler processes high-frequency traffic without yielding, the "Idle Task" and "Wi-Fi Stack" can't run. This leads to internal descriptor corruption or watchdog triggers. A vTaskDelay(1) gives the system exactly enough time to clear the network buffers and reset the watchdog.

**Comment by Keyunge** [comment]
I fixed! I was just calling function 2 times, sorry "^^
