### ISSUE TITLE
Single char converted to ASCII code instead of string

### ISSUE THREAD

**Issue by sulliwane** [nlohmann/json#413]
Hello,

I'm getting two types of data in a api callback function:
```cpp
typedef char type1;
typedef char type2[16];
```
and here is my function:
```cpp
void spi::OnCallback(Message *message) {
  json data = json({});
  
  data["type1"] = message->type1;  // message.type1 === 'A'
  data["type2"] = message->type2; // message.type2 === 'a string'

  DEBUG(data.dump());
// data.type1 === 60
// data.type2 === 'a string'
};
```
Type2 is recognized as a string by the json lib, but it seems type1 being a single char is converted to the equivalent ASCII number. I'm a correct? So right now I handle this by explicitly converting the single char to a string like this: 
```cpp
data["type1"] = std::string(1, message->type1);
```
But this is not really convenient. Any idea on how to better handle this single char case, so that it's implicitly converted to a string by the library?

Many thanks for your help!

**Comment by nlohmann** [comment]
I understand the issue, but I fear that implicitly converting a single character to a string could be surprising, because `std::string` has no such implicit conversion. I tried to make `basic_json` behave like a `std::string` when storing JSON strings.

For your convenience, you may implement a function like

```cpp
json from_char(char c)
{
    return std::string(1, c);
}
```

**Comment by jaredgrubb** [comment]
char is weird and the STL treats the three types [char/signed char/unsigned char] inconsistently, in my opinion. For example, "std::cout << ((uint8_t)65)" will print "A", but "std::cout << ((uint16_t)65)" prints a number.

In my ideal world, 'char' would represent a character (not a number!) and 'signed char'/'unsigned char' (aka int8_t, uint8_t) would represent numeric values. There are three distinct types, but the STL gives them no semantic difference.

For purity, adding "basic_json(char) = delete" removes confusion because every implicit conversion doesn't make sense (either as a character or a number); note that uint8_t and int8_t still convert as a number.

But, in practice, I do not think it's worth the breaking change.

**Comment by sulliwane** [comment]
I see, so I will continue with manual conversion to a string.

Many thanks both of you for your answers, very helpful :)

**Comment by nlohmann** [comment]
I also agree that deleting the `basic_json(char)` constructor is not worth it.

Thanks for the discussion! I shall add a not to the documentation.
