### ISSUE TITLE
struct reflect json with error C2440

### ISSUE THREAD

**Issue by sc-bai** [nlohmann/json#4467]
### Description

![image](https://github.com/user-attachments/assets/3d900a21-78c0-4872-b8ea-bfbdbfc11613)
I have a try with this json. but it error with error C2440:
Do I have a use error

### Reproduction steps

![image](https://github.com/user-attachments/assets/3d900a21-78c0-4872-b8ea-bfbdbfc11613)
I have a try with this json. but it error with error C2440:
Do I have a use error

### Expected vs. actual results

![image](https://github.com/user-attachments/assets/3d900a21-78c0-4872-b8ea-bfbdbfc11613)
I have a try with this json. but it error with error C2440:
Do I have a use error

### Compiler and operating system

win

### Library version

last

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by sc-bai** [comment]
sorry for this, but i want do this with reflect. struct & json

**Comment by sc-bai** [comment]
is anyone here ?

**Comment by nlohmann** [comment]
In order to asses your issue, we need the following information:

- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by sc-bai** [comment]
> In order to asses your issue, we need the following information:
> 
> * What is the issue you have?
> * Please describe the steps to reproduce the issue. Can you provide a small but working code example?
> * What is the expected behavior?
> * And what is the actual behavior instead?
> * Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?
> * Did you use a released version of the library or the version from the `develop` branch?
> * If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

I got it with NLOHMANN_DEFINE_TYPE_INTRUSIVE.
struct person {
	std::string name;
	std::string address;
	int age;
	**NLOHMANN_DEFINE_TYPE_INTRUSIVE(person, name, address, age)**
};

now, it can be work now. but your readme didnot say about it.
you can close it now.thanks.
nlohmann json is a nice lib for reflect. thanks for your work
