### ISSUE TITLE
VC++2017 not enough actual parameters for macro 'max'

### ISSUE THREAD

**Issue by pavel-pimenov** [nlohmann/json#522]
VC++2017

![default](https://cloud.githubusercontent.com/assets/920705/24073246/98e3f4a8-0c05-11e7-8e6f-8f82dbbe44e2.png)

**Comment by nlohmann** [comment]
This seems to be related to #506. Please check the `develop` version where we added parentheses around the min/max calls to fix this MSVC error.

(Note that the `develop` branch is unreleased and subject to change until version 3.0.0)

**Comment by BigJim** [comment]
For the record has the same problem, and another similar error.

The problem was not at all the json header code, but other header files defining things that conflict with STD, STL, defaults.
My project has a couple of large dependencies with a lot of header files.

I only have #include "json.hpp" in one place and so I just had to put two "#undef" statements before it.
In Visual Studio highlight the problem define and press F12 (the default jump to definition key) so you can see where the problem origionated.
