### ISSUE TITLE
Exception objects must be nothrow copy constructible (ERR60-CPP)

### ISSUE THREAD

**Issue by nlohmann** [nlohmann/json#531]
The SEI CERT C++ Coding Standard states in ERR60-CPP:

> If the copy constructor for the exception object type throws during the copy initialization, std::terminate() is called, which can result in undefined behavior.

The user-defined exceptions all base on `detail::exception` which has a `std::string` member. The exceptions have to be refactored to satisfy `std::is_nothrow_copy_constructible`.

**Comment by jaredgrubb** [comment]
Std::string would only throw if you run out of memory, right? The exceptions you're discussing would have strings that have ~100 bytes in them. If you run out of memory over 100 bytes, I dont think anyone actually expects to recover from that.

I agree that this is a good goal, but personally, I treat things like std::string as effectively no-throw because there's no chance a program can recover from extreme low-memory like that.

**Comment by nlohmann** [comment]
I agree that this is not a major issue. I just wanted to document it and maybe add more problems later. The document also proposes a fix I have not tried yet.

**Comment by nlohmann** [comment]
Some references:

- http://stackoverflow.com/a/15853984/266378
- http://www.boost.org/community/error_handling.html

**Comment by nlohmann** [comment]
The issue can be fixed by storing the message inside a `std::runtime_exception` object. Then, our exceptions are nothrow copy constructible  if `std::runtime_exception` is.

The fix 53b501a785f94250fe7b359b8ba6288d495aad5d can be merged when the CI builds complete.
