### ISSUE TITLE
Removing item from array

### ISSUE THREAD

**Issue by drewpts** [nlohmann/json#56]
Hi. Thanks for great lib!
Is there support for removing item/items from array?

E.g.:
 ```cpp
        json j;
        j["name"] = { "testname", "yetanothername" };
        j["name"].erase("testname");
```
    $ ./a.out 
    terminate called after throwing an instance of 'std::runtime_error'
    what():  cannot use at with array

**Comment by mkwork** [comment]
Anyway, copy-pasted code detected. There are lying comments and wrong error message in this method.

**Comment by nlohmann** [comment]
There is currently no function to delete elements from an array. This should be offered to have a "symmetrical" feature set compared to objects.

The text of the exception you reported is correct: the type of `j["name"]` is an array, therefore "cannot use at with array" is correct.

**Comment by mkwork** [comment]
Hm, but there isn't used ```at()```? Or i missunderstood you.

**Comment by nlohmann** [comment]
Oops... I'll fix that... :-)

**Comment by nlohmann** [comment]
Fixed the comment in 1bdb6acb1fb003a9bb8cb7771618f1630e78f7d0.

**Comment by nlohmann** [comment]
84195daf287a06d68ec0a1e0434b90eb44adb41b implements an erase functions for arrays:

```cpp
void erase(const size_type pos)
```

This function removes the element at the given index `pos`. All following elements are moved forward. If `pos` is an invalid array index, `std::out_of_range` is thrown.

Compared to the initial example, I decided against passing a value to delete, because a value can occur multiple times and the result could be unexpected.

I hope this helps.

**Comment by drewpts** [comment]
@nlohmann my thanks!
I'll check it up by my side.

**Comment by mkwork** [comment]
Wow, thanks for so fast issue fix :)
