### ISSUE TITLE
Operator= ambiguous in C++1z and GCC 7.1.1

### ISSUE THREAD

**Issue by nick-prat** [nlohmann/json#670]
With the new GCC 7.1.1 there is a bug with reassigning to strings.

In this code
```cpp
#include <string>
#include <iostream>
#include <json.hpp>

using json = nlohmann::json;

int main() {
    json js;
    std::string name = "";
    name = js["name"];
}
```
it produces the error
```
In file included from /usr/include/c++/7.1.1/string:52:0,
                 from json_error.cc:1:
/usr/include/c++/7.1.1/bits/basic_string.h: In instantiation of ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_If_sv<_Tp, std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&> std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator=(_Tp) [with _Tp = nlohmann::basic_json<>; _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_If_sv<_Tp, std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&> = std::__cxx11::basic_string<char>&]’:
json_error.cc:10:21:   required from here
/usr/include/c++/7.1.1/bits/basic_string.h:764:28: error: call of overloaded ‘assign(nlohmann::basic_json<>&)’ is ambiguous
  { return this->assign(__sv); }
                            ^
/usr/include/c++/7.1.1/bits/basic_string.h:1313:7: note: candidate: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::assign(const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]
       assign(const basic_string& __str)
       ^~~~~~
/usr/include/c++/7.1.1/bits/basic_string.h:1329:7: note: candidate: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::assign(std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]
       assign(basic_string&& __str)
       ^~~~~~
/usr/include/c++/7.1.1/bits/basic_string.h:1440:7: note: candidate: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::assign(std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::__sv_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::__sv_type = std::basic_string_view<char>]
       assign(__sv_type __sv)
       ^~~~~~
```
when built with `g++ -std=c++1z filename.cpp` but it will compile fine with `c++ -std=c++14 filename.cpp`

this also occurs if using clang if the GCC libs version is 7.1.1

**Comment by nlohmann** [comment]
I cannot reproduce this on macOS with g++ (GCC) 8.0.0 20170726 (experimental) with `-std=c++1z`.

**Comment by nlohmann** [comment]
We further run GCC 7.1.0 with `-std=c++17` without problems, see https://travis-ci.org/nlohmann/json/jobs/259074844.

**Comment by nlohmann** [comment]
May this be a bug in GCC?

**Comment by nlohmann** [comment]
Maybe related: #667

**Comment by nlohmann** [comment]
Cannot reproduce.

**Comment by lieff** [comment]
Can reproduce this on CentOS 7.6 machine using 7.2.1. Not reproduced on Ubuntu with gcc 5.3 and 8.1.

**Comment by nickaein** [comment]
It can be reproduced for version 3.5.0 of library using GCC 7.1.0 on Godbolt with `-std=c++1z` and even with `-std=c++17` flag: https://godbolt.org/z/ff1t3Z. It compiles with `-std=c++14` flag though. 

Based on [this documentation](https://en.cppreference.com/w/cpp/compiler_support) (under section **Refereneces**), while GCC support of C++17 core language has be complete since 7.1, the library support wasn't (and still isn't). 

Therefore, this is either caused by a bug in GCC 7.1.0 (which seems unlikely as it cannot be reproduced in other environments) or an oversight in the `libstdc++` that has been fixed in later versions.

#### Note on `-std=c++1z`

I'm not sure how far we should go to support it. The latest GCC documentation states that [`c++1z` has been deprecated](https://gcc.gnu.org/onlinedocs/gcc/C-Dialect-Options.html). Also, [the documentation on GCC 7.1.0](https://gcc.gnu.org/onlinedocs/gcc-7.1.0/gcc/C-Dialect-Options.html) states that (emphasis mine):

> `c++1z`: The next revision of the ISO C++ standard, tentatively planned for 2017. **Support is highly experimental, and will almost certainly change in incompatible ways in future releases**.

So I believe `c++1z` should be abandoned in favor of `-std=c++17`.
