### ISSUE TITLE
There is performance inefficiency found by coverity tool json2.1.1/include/nlohmann/json.hpp

### ISSUE THREAD

**Issue by qinglucich** [nlohmann/json#673]
4063    @since version 1.0.0
4064    */
4065    template<class ValueType, typename std::enable_if<
4066                 std::is_convertible<basic_json_t, ValueType>::value, int>::type = 0>
    	
CID 10413 (#1 of 1): Big parameter passed by value (PASS_BY_VALUE)
pass_by_value: Passing parameter default_value of type cerebras::file_metadata (size 168 bytes) by value.
4067    ValueType value(const typename object_t::key_type& key, ValueType default_value) const
4068    {

**Comment by nlohmann** [comment]
Thanks for reporting. Here is the line in context: https://github.com/nlohmann/json/blob/v2.1.1/src/json.hpp#L4066

**Comment by nlohmann** [comment]
This is also relevant for 3.0.0.

**Comment by nlohmann** [comment]
Fixed. Thanks for reporting!

**Comment by murderotica** [comment]
Wouldn't using universal reference instead of `const&` be better (in case of an r-value a move is will be possible instead of always copy)?

This
`
ValueType value(const json_pointer& ptr, const ValueType& default_value)
`
replaced with this

`
ValueType value(const json_pointer& ptr, ValueType&& default_value)
{
 //...
 JSON_CATCH (out_of_range&)
 {
     return std::forward<ValueType>(default_value);
 }
}
`

reference example [](https://godbolt.org/g/Vvi9ms)

**Comment by theodelrieu** [comment]
There is quite a lot of room for zero-copy/rvalue references support in the library indeed.

Note that the return type should be changed to `auto (...) -> decltype(std::forward<ValueType>(default_value))` to avoid copies.

**Comment by nlohmann** [comment]
@murderotica, @theodelrieu Can you create a PR for these optimizations?

**Comment by theodelrieu** [comment]
I'll add that to my TODO list.

**Comment by nlohmann** [comment]
Thanks!
