### ISSUE TITLE
Thread safety of parse()

### ISSUE THREAD

**Issue by tanaynv** [nlohmann/json#800]
Hi,

I plan to use this library to parse JSON files in a multithreaded environment. Specifically I am concerned about thread safety with respect to the behaviour of parse() when called simultaneously from different threads. I would appreciate any help or input on this matter. 

Thanks, 
Tanay

**Comment by nlohmann** [comment]
Internally, the library uses `std::map`, `std::vector` and `std::string` to store values. `parse` goes sequentially through the input and creates values on the fly. Calling `parse` from a different thread _on the same `json` value_ will most likely be problematic.

Something like:

- Thread 1: `json j1 = json::parse(...);`
- Thread 2: `json j2 = json::parse(...);`

should be safe, because the two values `j1` and `j2` do not share any state.

**Comment by nlohmann** [comment]
@tanaynv Do you need any further information?

**Comment by tanaynv** [comment]
Hi Niels, 
Thank you very much for your reply, it was helpful. I need no further information at this point.
