### ISSUE TITLE
how to print out the line which causing exception?

### ISSUE THREAD

**Issue by todatamining** [nlohmann/json#806]
Something wrong with my json, but it just print out:

[json.exception.type_error.302] type must be array, but is null

From the error, it is hard to tell which line is wrong in the json file or my code, is there a way to print out the line causing exception?

update:
I check the json, the error is causing by the following line:

{
       "email": [....]
}

in the code, there is a typo

vector<string> emails =  info["emails"]; //should be "email"

is it possible to print out the line#?

**Comment by nlohmann** [comment]
No, this is not possible. Once the JSON text is parsed and the `json` value is constructed, the line numbers are discarded. However, the stack trace of the thrown exception should give you the exact line of the implicit conversion that failed.

**Comment by nlohmann** [comment]
(Explanation for the error: when you call `info["emails"]` on a non-const `json` object, the `[]` creates `null` entries when it does not find an element at key `"emails"`. As `null` cannot be converted to an array-like container such as `std::vector`, exception 302 occurs. Note this is not a parse error, as the JSON object is perfectly fine. Therefore, we cannot provide a line number. If you had used `info.at("emails")` instead of `info["emails"]`, an exception would have indicated that the object does not contain an entry with key `"emails"`, which would have made diagnostics easier.)

**Comment by todatamining** [comment]
Great! Thanks.
