### ISSUE TITLE
Discuss: replace static "iterator_wrapper" function with "items" member function

### ISSUE THREAD

**Issue by nlohmann** [nlohmann/json#874]
The static `iterator_wrapper` function is a means to access objects' keys in a range for. Example:

```cpp
json j_object = {{"one", 1}, {"two", 2}};

for (auto& x : json::iterator_wrapper(j_object)) {
    std::cout << "key: " << x.key() << ", value: " << x.value() << '\n';
}
```

I never was happy about the name of the function and there were several issues where users expected `json` to behave as a map so that `.first` and `.second` could be used.

## Question 1

As for the name: What about replacing the static `iterator_wrapper` function by a member function `items` (name motivated by Python)?

Usage:

```cpp
json j_object = {{"one", 1}, {"two", 2}};

for (auto& x : j_object.items()) {
    std::cout << "key: " << x.key() << ", value: " << x.value() << '\n';
}
```

## Question 2

One could even think about supporting `.first` and `.second`, but this would mean pre-computing the values for `.key()` and `.value()` which would mean a bit of overhead.

What do you think?

**Comment by gregmarr** [comment]
I think adding the `.items()` would be useful to make it less verbose.  Having `.first` and `.second` would mean that you'd have to add a `std::string` and a `std::reference_wrapper` to the type.  This would increase the size, and potentially change semantics of `.value()`, because the type would be something like `std::reference_wrapper<std::remove_reference<IteratorType::reference>::type>` instead of just `IteratorType::reference`.  The semantics are already a bit different than iterating over a map as it allows you to iterate over an array and get the indices as strings, so I don't think having `.key()` and `.value()` makes it that much more difficult to use.

**Comment by nlohmann** [comment]
Any further comments?

**Comment by gregmarr** [comment]
Oh, thanks for referencing this, it points out that I missed something in my evaluation on the deduction guides issue.

**Comment by gregmarr** [comment]
Just one more: we don't necessarily need to remove `.value()` or make it return `.second`, so we can do this without changing the semantics of `.value()`.

I'd say add `.items()` now.  It's independent from `.first`/`.second` and we can continue that bit via #901.

**Comment by nlohmann** [comment]
Instead of adding `.items()`, I would like to replace `iterator_wrapper` with it. I think `iterator_wrapper` should be deprecated with the next release.

**Comment by gregmarr** [comment]
To follow semver, we need to deprecate it now and remove it in 4.0.

**Comment by nlohmann** [comment]
Right, this is what I meant.

**Comment by nlohmann** [comment]
`iterator_wrapper` is now deprecated and will be removed in 4.0.0.

**Comment by Anthony-J-Garot** [comment]
A note in https://github.com/nlohmann/json/blob/develop/doc/examples/iterator_wrapper.cpp would be helpful.

**Comment by nlohmann** [comment]
@Anthony-J-Garot I did so in https://github.com/nlohmann/json/commit/be1eafa12cc05bb2f7971fb170b2703526748cb7 which should be merged to develop soon(ish).
