### ISSUE TITLE
init error

### ISSUE THREAD

**Issue by likebeta** [nlohmann/json#92]
code:
```c++
#include <iostream>
using namespace std;

#define print(j) cout << " " #j  << ": " << j  << endl

int main(int argc, char** argv)
{
 	// case 1
	json j = {
		{ "limit", 1000 },
		{ "reward", {{ "chip", 1000 },{ "chip", 2000 },{ "chip", 3000 }}}
	};
	print(j);

	// case 2
	j = {
		{ "limit", 1000 },
		{ "reward", json::array({ { "chip", 1000 }, { "chip", 2000 }, { "chip", 3000 } }) }
	};
	print(j);

	// case 3
	j["limit"] = 1000;
	j["reward"] = json::array({ { "chip", 1000 }, { "chip", 2000 }, { "chip", 3000 } });
	print(j);

	return 0;
}
```
output:
```sh
[king@localhost Project1]$ sh make.sh 
 j: {"limit":1000,"reward":{"chip":1000}}
 j: {"limit":1000,"reward":[["chip",1000],["chip",2000],["chip",3000]]}
 j: {"limit":1000,"reward":[["chip",1000],["chip",2000],["chip",3000]]}
```

It is strange  in case 1,  why get this result?

**Comment by ropuls** [comment]
Hi,

in 1), you're initializing the reward with an object type (aka map). This is exactly the same as initializing a map like this:
```c++
    std::map<std::string, std::string> m = {
        {"key", "val"},
        {"key", "xxx"}
    };

    printf("%s\n", m["key"].c_str());
```
the result will be: ```val```, not ```xxx```. This is due to the fact that the map will not replace key's value if it's already present during brace-initialization.

Assuming you want reward to be an array of objects, you would need to:

```c++
    json j = {
        { "limit", 1000 },
        { "reward",
          {
              {{ "chip", 1000 }},
              {{ "chip", 2000 }},
              {{ "chip", 3000 }}
          }
        }
    };
```
which gives you a
```
{"limit":1000,"reward":[{"chip":1000},{"chip":2000},{"chip":3000}]}
```
If you want reward to be an array of arrays, then most likely json::array constructs are needed.

Hope it helps,
  Roman

**Comment by likebeta** [comment]
Think you very mush. It is very helpful to me. Now I know the reason. I was hoping for yourexample!

If for some reason, I just want a result as `{"limit":1000,"reward":[["chip",1000],["chip",2000],["chip",3000]]}`, how to make it? Must I use `json::array`?

Thanks again

**Comment by nlohmann** [comment]
Hi @likebeta,

the problem is that C++ only supports `{` and `}` in initializer lists. For JSON, however, it would be convenient to have two different sets of braces to differentiate between objects and arrays. To this end, I decided to process initializer lists as follows:

1. If a list contains only elements which are itself lists with two elements *and* each of the two-element lists has a string as first element, then I treat this as an object.
2. Anything else is an array.

So in your example `{{ "chip", 1000 },{ "chip", 2000 },{ "chip", 3000 }}` is exactly an instance of the first rule: the list has three elements, each element is a list of two elements, and each entry has a string as first element. The fact that you use `"chip"` as key for all elements makes it even more confusing...

So when you want this to be treated as array, you need to tell it explicitly by

```cpp
json::array({
  { "chip", 1000 }, { "chip", 2000 }, { "chip", 3000 }
})
```

In fact, this is one of the few situations where you need to help the class to understand what you want.

Sorry for the inconvenience. And thanks to @ropuls for the quick explanation.

Cheers
Niels

**Comment by likebeta** [comment]
@nlohmann @ropuls Think you very mush!
