### ISSUE TITLE
Uniform initialization from another json object differs between gcc and clang.

### ISSUE THREAD

**Issue by dsiroky** [nlohmann/json#985]
Construction behaves differently with gcc 7.2 and clang 5.

Code to reproduce:
```
auto j1{nlohmann::json::parse("5")};
auto j2 = nlohmann::json::parse("5");
std::cout << j1.is_array() << '\n';
std::cout << j2.is_array() << '\n';
```

gcc prints:
1
0

clang prints:
0
0

Both are nlohmann::json instances however `j1` has an array wrapped around in gcc.

**Comment by theodelrieu** [comment]
IIRC the `auto i{2}` form has been fixed in C++17, before it would deduce to `std::initializer_list` instead of `int`.

I guess this is the same thing here. If you enable more warnings you should see Clang tell you something like "the meaning of this initialization will change in the future".

My recommendation would be to not use it at all, uniform initialization is quite borken :/

**Comment by nlohmann** [comment]
I fear there is nothing we can do about this. :-/
